<html>
    <head>
        <title><?= $title ?> - eBuildy Error</title>
        <style>
            * {
                margin:0;
                padding:0;
                word-break: break-all;
            }
            
            a 
            {
                color:#111;
            }
            
            body {
                background:#eee;
                color:#333;
                font:11px Verdana, Arial, sans-serif;
            }
            
            .content {
                margin:20px auto;
                width: 1000px;
            }
            
            .block {
                background:#fff;
                padding:30px;
                border:1px solid #d1d1d2;
                border-radius: 10px;
                margin: 10px 0;
            }
            
            .trace
            {
                margin:10px 0;
            }
            
            ol
            {
                border: 1px solid #D1D1D2;
                margin: 10px;
                list-style-type: decimal;
            }
            
            ol li
            {
                padding: 3px;
            }
            
            ol li:nth-child(odd)
            {
                background:#F0F0F0;
            }
            
            .good_line
            {
                background:rgb(255, 170, 77);
            }
        </style>
    </head>
    <body>
        <div class="content">
            <div class="block">
                <h1><?= nl2br($title) ?></h1>
                <h2><?= 2 ?></h2>
                <h4><?= resolveFilePath($file) ?> [<?= $line ?>]</h4>
                <?= readSourcePortion($file, $line) ?>
            </div>
            
                        <div class="block">
                <h2>Debug log</h2>
                <table>
                <?php foreach($debugLogs as $log): ?>
                <tr><td><?= $log["name"] ?></td><td><?= json_encode($log["value"]) ?></td></tr>
                <?php endforeach ?>
                </table>
            </div>
            
            <div class="block">
                <?php foreach($trace as $item): ?>
                <div class="trace">
                    <?php
                        $file = $item['file'];
                        $line = $item['line'];
                    
                        $buffer = explode('/', $item['file']);
                        $filename = $buffer[count($buffer) - 1];
                    ?>
                    <div>
                        <h2><?= $item['caller'] ?>(<?= join(', ', $item['args']) ?>)</h2>
                        <b><?= $filename ?></b>  [<?= $item['line'] ?>]</div>
                    <?= readSourcePortion($file, $line) ?>
                    <?= resolveFilePath($item['file']) ?>
                </div>
                <?php endforeach ?>
            </div>
            <a href="//ebuildy.com">http://ebuildy.com</a>
        </div>
    </body>
</html>
<?php

    function resolveFilePath($file)
    {
        return str_replace(realpath(ROOT), '', $file);
    }
    
    function readSourcePortion($file, $line)
    {
        $buffer = "";
        
        $line--;
        
        $lines = file($file, FILE_IGNORE_NEW_LINES);
        
        for($i = max(array(0, $line - 5)); $i < min(count($lines), $line + 5); $i++)
        {
            $buffer .= '<li '. ($i == $line ? 'class="good_line"' : '') .'>' . str_replace(array('&lt;?php'), '', highlight_string('<?php ' . $lines[$i], true)) . "</li>" . PHP_EOL;
        }
        
        return '<ol start="' . (max(array(0, $line - 4))) . '">' . $buffer . '</ol>';
    }
    
?>